"""Work item creation service for Azure DevOps."""

from __future__ import annotations

import structlog

from app.config import get_settings
from app.models.schemas import CreateStoryRequest, CreateStoryResponse, ComplianceResult
from app.services.ado_client import ADOClient

logger = structlog.get_logger()


class WorkItemService:
    """Creates Azure DevOps work items for migration tasks."""

    async def create_migration_story(
        self, request: CreateStoryRequest
    ) -> CreateStoryResponse:
        """Create a User Story work item in ADO for migration."""
        settings = get_settings()
        client = ADOClient()

        title = (
            f"[MigrationLens] Migrate {request.repo_name} to .NET 10 "
            f"(Score: {request.compliance_score:.0f}%)"
        )

        description = self._build_description(request)

        project = settings.ado_project or "DefaultProject"

        result = await client.create_work_item(
            project=project,
            title=title,
            description=description,
            priority=request.priority,
            tags="MigrationLens,dotnet-migration,net10",
        )

        work_item_id = result.get("id", 0)
        url_parts = result.get("_links", {}).get("html", {})
        url = url_parts.get("href", f"{settings.ado_base_url}/{project}/_workitems/edit/{work_item_id}")

        logger.info("work_item_created", id=work_item_id, repo=request.repo_name)

        return CreateStoryResponse(
            work_item_id=work_item_id,
            url=url,
            title=title,
        )

    def _build_description(self, request: CreateStoryRequest) -> str:
        """Build work item description from failing rules."""
        lines = [
            f"<h2>Migration Required: {request.repo_name}</h2>",
            f"<p><strong>Current Compliance Score:</strong> {request.compliance_score:.1f}%</p>",
            "<h3>Failing Rules</h3>",
            "<table>",
            "<tr><th>Rule</th><th>Category</th><th>Severity</th><th>Details</th></tr>",
        ]

        for rule in request.failing_rules:
            lines.append(
                f"<tr><td>{rule.rule_id}: {rule.rule_name}</td>"
                f"<td>{rule.category}</td>"
                f"<td>{rule.severity}</td>"
                f"<td>{rule.details}</td></tr>"
            )

        lines.append("</table>")
        lines.append("<h3>Acceptance Criteria</h3>")
        lines.append("<ul>")
        lines.append("<li>All critical compliance rules pass</li>")
        lines.append("<li>Overall compliance score ≥ 90%</li>")
        lines.append("<li>All unit tests pass with .NET 10</li>")
        lines.append("<li>CI/CD pipeline updated for .NET 10 SDK</li>")
        lines.append("</ul>")
        lines.append(f"<p><em>Generated by MigrationLens</em></p>")

        return "\n".join(lines)
