"""AI analysis endpoints — code analysis, risk assessment, migration planning."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Path, Query

from app.config import get_settings
from app.models.enums import ComplianceStatus
from app.models.schemas import (
    AIAnalysisResponse,
    AICodeAnalysis,
    AIInsight,
    AIMigrationPlan,
    AIMigrationPhase,
    AIMigrationTask,
    AIPRSuggestion,
    AIBreakingChange,
    AIRecommendation,
    AIRiskAssessment,
    AIRiskFactor,
)
from app.services import ai_service
from app.services.cache import CacheManager

router = APIRouter()


def _find_scan_result(cache: CacheManager, repo_id: str, organization: str = ""):
    """Search for a repo's scan results in cached data."""
    if organization:
        data = cache.load(organization)
        if data:
            results = data.repositories or data.scan_results or []
            for result in results:
                if result.repository.id == repo_id:
                    return result
    # Search all cache files
    from pathlib import Path as FilePath
    cache_dir = FilePath(cache._cache_dir)
    if cache_dir.exists():
        for f in cache_dir.glob("dashboard_*.json"):
            if f.name.endswith(".meta.json"):
                continue
            org_name = f.stem.replace("dashboard_", "")
            data = cache.load(org_name)
            if data:
                results = data.repositories or data.scan_results or []
                for result in results:
                    if result.repository.id == repo_id:
                        return result
    return None


@router.get("/repos/{repo_id}/ai-analysis", response_model=AIAnalysisResponse)
async def get_ai_analysis(
    repo_id: str = Path(..., description="Repository ID"),
    organization: str = Query("", description="ADO organization name"),
) -> AIAnalysisResponse:
    """Run AI-powered analysis on a scanned repository.

    Returns code analysis insights, risk assessment, and a phased migration plan
    generated by Azure OpenAI.
    """
    settings = get_settings()
    org = organization or settings.ado_organization

    cache = CacheManager()
    scan_result = _find_scan_result(cache, repo_id, org)

    if not scan_result:
        raise HTTPException(
            status_code=404,
            detail="Repository not found in scan data. Please scan the repository first.",
        )

    # Prepare data for AI
    failing_rules = [
        {
            "rule_id": r.rule_id,
            "rule_name": r.rule_name,
            "category": r.category,
            "severity": r.severity.value if hasattr(r.severity, "value") else str(r.severity),
            "details": r.details,
            "file_path": r.file_path,
            "suggested_fix": r.suggested_fix,
        }
        for r in scan_result.compliance_results
        if r.status == ComplianceStatus.FAIL
    ]

    passing_rules = [
        {
            "rule_id": r.rule_id,
            "rule_name": r.rule_name,
            "category": r.category,
            "severity": r.severity.value if hasattr(r.severity, "value") else str(r.severity),
        }
        for r in scan_result.compliance_results
        if r.status == ComplianceStatus.PASS
    ]

    category_scores = [
        {
            "category": cs.category,
            "score": cs.score,
            "passed": cs.passed,
            "failed": cs.failed,
        }
        for cs in scan_result.category_scores
    ]

    # Build file snippets from compliance results (code found in scan)
    file_snippets: dict[str, str] = {}
    for r in scan_result.compliance_results:
        if r.file_path and r.current_code:
            file_snippets.setdefault(r.file_path, "")
            file_snippets[r.file_path] += f"\n// [{r.rule_id}] Line {r.line_number}:\n{r.current_code}\n"

    repo_name = scan_result.repository.name
    current_version = scan_result.dotnet_version or scan_result.repository.dotnet_version or "unknown"
    complexity = scan_result.complexity.value if hasattr(scan_result.complexity, "value") else str(scan_result.complexity)

    # Run all AI tasks in parallel
    import asyncio

    code_task = ai_service.analyze_code(repo_name, failing_rules, file_snippets)
    risk_task = ai_service.assess_risk(
        repo_name, current_version, scan_result.overall_score,
        failing_rules, category_scores, complexity, scan_result.project_count,
    )
    plan_task = ai_service.generate_migration_plan(
        repo_name, current_version, "net10.0",
        failing_rules, passing_rules, category_scores,
    )

    code_raw, risk_raw, plan_raw = await asyncio.gather(
        code_task, risk_task, plan_task,
        return_exceptions=True,
    )

    # Parse code analysis
    code_analysis = AICodeAnalysis()
    if isinstance(code_raw, dict):
        code_analysis = AICodeAnalysis(
            summary=code_raw.get("summary", ""),
            insights=[
                AIInsight(**i) for i in code_raw.get("insights", [])
                if isinstance(i, dict)
            ],
            recommendations=[
                AIRecommendation(**r) for r in code_raw.get("recommendations", [])
                if isinstance(r, dict)
            ],
        )

    # Parse risk assessment
    risk_assessment = AIRiskAssessment()
    if isinstance(risk_raw, dict):
        risk_assessment = AIRiskAssessment(
            risk_level=risk_raw.get("risk_level", "medium"),
            risk_score=risk_raw.get("risk_score", 50),
            effort_estimate_days=risk_raw.get("effort_estimate_days", 5),
            risk_factors=[
                AIRiskFactor(**f) for f in risk_raw.get("risk_factors", [])
                if isinstance(f, dict)
            ],
            mitigation_suggestions=risk_raw.get("mitigation_suggestions", []),
            confidence=risk_raw.get("confidence", 70),
        )

    # Parse migration plan
    migration_plan = AIMigrationPlan()
    if isinstance(plan_raw, dict):
        phases = []
        for p in plan_raw.get("phases", []):
            if isinstance(p, dict):
                tasks = [
                    AIMigrationTask(**t) for t in p.get("tasks", [])
                    if isinstance(t, dict)
                ]
                phases.append(AIMigrationPhase(
                    name=p.get("name", ""),
                    description=p.get("description", ""),
                    order=p.get("order", 0),
                    tasks=tasks,
                    estimated_hours=p.get("estimated_hours", 0),
                ))
        migration_plan = AIMigrationPlan(
            phases=phases,
            estimated_total_hours=plan_raw.get("estimated_total_hours", 0),
            pr_suggestions=[
                AIPRSuggestion(**s) for s in plan_raw.get("pr_suggestions", [])
                if isinstance(s, dict)
            ],
            breaking_changes=[
                AIBreakingChange(**b) for b in plan_raw.get("breaking_changes", [])
                if isinstance(b, dict)
            ],
        )

    ai_available = bool(settings.azure_openai_endpoint and settings.azure_openai_api_key)

    return AIAnalysisResponse(
        code_analysis=code_analysis,
        risk_assessment=risk_assessment,
        migration_plan=migration_plan,
        ai_available=ai_available,
    )


@router.get("/ai/health")
async def ai_health():
    """Check Azure OpenAI connectivity."""
    return await ai_service.check_ai_health()
